config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'questions#index'
  get 'confirmation' => 'confirmation#confirmation'
  post 'send_confirmation_of_email' => 'confirmation#send_confirmation_of_email'


  concern :votable do
    member do
      post :vote
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: [:create]
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true, only: [:create, :destroy, :update] do
      member do
        patch 'set_the_best'
      end
    end
    resources :subscribes, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  get :search, to: 'search#index'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable


  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :subscribes, dependent: :destroy

  validates :title, :body, presence: true

  scope :sorted, -> { order(created_at: :desc) }
  scope :last_day, -> { where('created_at >= ?', (Date.today - 1.day).to_datetime) }

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  after_create :subscribe_me


  private

  def subscribe_me
    self.subscribes.create(user_id: self.user_id)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :set_question, only: :show

  authorize_resource class: Question

  def index
    respond_with(Question.all, each_serializer: QuestionListSerializer)
  end

  def show
    respond_with @question, each_serializer: QuestionSerializer
  end

  def create
    respond_with@question = current_resource_owner.questions.create(question_params)
  end


  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question
    @question = Question.find params[:id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :update, :destroy]

  after_action :publish_question, only: [:create]

  respond_to :js, only: :update

  authorize_resource


  def index
    gon.question = Question.last
    respond_with(@questions = Question.all.sorted)
  end


  def new
    respond_with(@question = Question.new)
  end


  def show
    @answer = Answer.new
    respond_with(@question)
  end


  def create
    respond_with(@question = current_user.questions.create(question_params))
  end


  def update
    @question.update(question_params)
    respond_with(@question)
  end


  def destroy
    respond_with @question.destroy
  end




  private

  def set_question
    @question = Question.find(params[:id])
  end


  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end


  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
        'questions',
        ApplicationController.render_with_signed_in_user(
          current_user,
          json: { question: @question }
        )
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.haml
%ul
  %li= answer.user.email
  %li= answer.body
  %li
  - if user_signed_in? && current_user.author_of?(answer)
    = link_to 'Delete', question_answer_path(@question, answer.id), method: :delete

app/views/questions/_form.html.haml
= form_for question, { remote: question.persisted?, html: { id: "edit-question-#{question.id}" } } do |f|
  = f.label :title
  = f.text_field :title

  = f.label :body
  = f.text_area :body

  %p Attachments:

  #attachments
    =  f.fields_for :attachments do |attachment|
      = render 'shared/attachments', f: attachment
    .links
      = link_to_add_association 'add file', f, :attachments, partial: 'shared/attachments'

  = f.submit 'Save'

app/views/questions/_question.html.haml
%hr
%div{ class: "question-#{question.id}" }
  %h3= link_to question.title, question_path(question)
  - if action_name == 'show'
    %p= question.body

  .subscribe
    - if current_user && current_user.has_subscribe?(question)
      = link_to 'Unsubscribe', subscribe_path(current_user.get_subscribe(question)), method: :delete, remote: true, class: 'unsubscribe-btn'
    - else
      - if can?(:create, Subscribe)
        = link_to 'Subscribe', question_subscribes_path(question), method: :post, remote: true, class: 'subscribe-btn'


  - if can?(:vote, question)
    %div{ class: 'voting' }
      %p
        %div{ class: "vote-links-#{question.id}" }
          = link_to 'vote up!', vote_question_path(question, user_vote: true), method: :post, remote: true, class: "vote-question-link", data: { question_id: question.id }
          = link_to 'vote for!', vote_question_path(question, user_vote: false), method: :post, remote: true, class: "vote-question-link", data: { question_id: question.id }
        - if question.voting_result
          %div{ class: "vote-#{question.id}" }
            %p= "#{question.voting_result[:positive_count]} (#{question.voting_result[:positive_persent]} %) / #{question.voting_result[:negative_count]} (#{question.voting_result[:negative_persent]}%) | #{question.voting_result[:result]}"


  - if question.attachments.any?
    %p Attachments:
    %ul
      - question.attachments.each do |a|
        %li= link_to a.file.identifier, a.file.url
        - if can?(:destroy, a)
          %li= link_to 'delete file', attachment_path(a), method: :delete


  - if can?(:destroy, question)
    = link_to 'Delete', question_path(question), method: :delete

  - if can?(:update, question) && action_name == 'show'
    %p= link_to 'Edit', '', class: 'edit-question-link', data: { question_id: question.id }
    = render 'questions/form', question: question


  - if action_name == 'show'
    = render 'shared/comment', commentable: question
%hr

app/views/questions/index.html.haml
- cache collection_cache_key_for :question do
  .questions
    = render @questions.sorted

= link_to 'Ask question', new_question_path
= render 'search/form'

app/views/questions/new.html.haml
- if @question.errors.any?
  = render 'shared/errors', object: @question

= render 'form', question: @question

app/views/questions/show.html.haml
- cache @question do
  .question{ data: { question_id: @question.id } }
    = render @question

.errors

.answers
  = render @question.answers.sorted

.answer-create
  - if user_signed_in?
    = form_for [@question, @answer], remote: true do |f|
      = f.label :body, 'answer'
      = f.text_area :body

      %br
      %p Attachments:

      #attachments
        = f.fields_for :attachments do |attachment|
          = render 'shared/attachments', f: attachment
        .links
          = link_to_add_association 'add file', f, :attachments, partial: 'shared/attachments'
      %br
      = f.submit 'Save'

  - else
    %p please sign in/sign up for answer

app/views/questions/update.js.erb
<% if @question.errors.any? %>
  $('.errors').html('<%= j render 'shared/errors', object: @question %>');
<% else %>
  $('.flash').html('<%= j render 'shared/flash' %>');
  $('.question-<%= @question.id %>').html('<%= j render @question %>');
  $('.edit_question').css('display', 'none')
<% end %>