config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'questions#index'
  get 'confirmation' => 'confirmation#confirmation'
  post 'send_confirmation_of_email' => 'confirmation#send_confirmation_of_email'


  concern :votable do
    member do
      post :vote
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: [:create]
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true, only: [:create, :destroy, :update] do
      member do
        patch 'set_the_best'
      end
    end
    resources :subscribes, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  get :search, to: 'search#index'

  mount ActionCable.server => '/cable'
end

app/models/search.rb
class Search

  def self.search(q, object="all")
    q = ThinkingSphinx::Query.escape(q) if !q.nil?

    if self.available_filters.include?(object)
      object.classify.constantize.search q
    else
      ThinkingSphinx.search q
    end
  end

  def self.filters
    [
      [nil, nil],
      ["Questions", "question"],
      ["Answers", "answer"],
      ["Comments", "comment"],
      ["Author", "user"]
    ]
  end


  private

  def self.available_filters
    %w(question answer comment user)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  authorize_resource class: Search

  def index
    respond_with @search_results = Search.search(params[:q], params[:object])
  end
end

app/views/search/_form.html.haml
%br
%br

= form_tag search_path, method: :get do
  .form-group
    = label_tag :object, "Search by:"
    = select_tag :object, options_for_select(Search.filters, params[:object])
  .form-group
    = search_field_tag :q, params[:q], placeholder: "Search"
  = submit_tag "Search"

app/views/search/index.html.haml
%h1 Search
%hr
= render "form", form_class: "form-inline"
%hr

.searches-list
  - if @search_results.blank?
    Where is no results searched
  - else
    - @search_results.each do |r|
      - if r.class.name == "Question"
        = link_to r.title, question_path(r)

      - elsif r.class.name == "Answer"
        %p= "Found a match in the answer for the question #{r.question.title}"
        = link_to r.question.title, question_path(r.question)

      - elsif r.class.name == "Comment"
        - if r.commentable.class.name == "Answer"
          = link_to "Found in answer #{r.commentable.id}, question-#{r.commentable.question.id} ", question_path(r.commentable.question)
        - else
          = link_to "Found in question #{r.commentable.title}", question_path(r.commentable)

      - elsif r.class.name == "User"
        %p= r.email
      %hr