config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'questions#index'
  get 'confirmation' => 'confirmation#confirmation'
  post 'send_confirmation_of_email' => 'confirmation#send_confirmation_of_email'


  concern :votable do
    member do
      post :vote
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: [:create]
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true, only: [:create, :destroy, :update] do
      member do
        patch 'set_the_best'
      end
    end
    resources :subscribes, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  get :search, to: 'search#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user

  has_many :attachments, as: :attachable, dependent: :destroy

  validates :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  scope :sorted, -> { order(:the_best, created_at: :desc) }

  after_create :notify_subscribed_user

  def set_the_best
    transaction do
      self.question.answers.update_all(the_best: nil)
      self.update!(the_best: true)
    end
  end

  def notify_subscribed_user
    NotifySubscribedUserJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :set_question, only: [:create]
  before_action :set_answer, except: :create
  before_action :load_question, only: :set_the_best

  after_action :publish_answer, only: [:create]

  respond_to :js

  authorize_resource


  def create
    respond_with(@answer = current_user.answers.create(answer_params.merge(question: @question)))
  end


  def update
    respond_with @answer.update(answer_params)
  end


  def destroy
    respond_with(@answer.destroy)
  end


  def set_the_best
    @question = @answer.question
    @answer.set_the_best
    respond_with @answer
  end



  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def load_question
    @question = @answer.question
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file])
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
        "answers_#{@question.id}",
        ApplicationController.render_with_signed_in_user(
            current_user,
            json: { answer: @answer,
                    author_of_answer: @answer.user,
                    attachments: @answer.attachments }
        )
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_answer, only: :show
  before_action :set_question, only: :create

  authorize_resource class: Answer

  def index
    @answers = Answer.all
    respond_with @answers
  end

  def show
    respond_with @answer
  end

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_resource_owner)))
  end


  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find params[:question_id]
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.haml
- if answer.persisted?
  - cache answer do
    %div{ class: "answer-#{answer.id}" }
      %ul
        - if answer.the_best
          %li
            %h4= answer.user.email
          %li
            %h4= answer.body
        -else
          %li= answer.user.email
          %li= answer.body

        - answer.attachments.each do |a|
          %li
            = link_to a.file.identifier, a.file.url
            - if can?(:destroy, a)
              = link_to 'delete file', attachment_path(a), method: :delete, remote: true


        - if can?(:set_the_best, answer)
          %p= link_to 'Best!', set_the_best_answer_path(answer), method: :patch, remote: true


        - if can?(:vote, answer)
          %div{ class: 'voting' }
            %p
              %div{ class: "vote-links-#{answer.id}" }
                = link_to 'vote up!', vote_answer_path(answer, user_vote: true), method: :post, remote: true, class: "vote-answer-link", data: { answer_id: answer.id }
                = link_to 'vote for!', vote_answer_path(answer, user_vote: false), method: :post, remote: true, class: "vote-answer-link", data: { answer_id: answer.id }
        %div{ class: "vote-#{answer.id}" }
          %p= "#{answer.voting_result[:positive_count]} (#{answer.voting_result[:positive_persent]}%) / #{answer.voting_result[:negative_count]} (#{answer.voting_result[:negative_persent]}%) | #{answer.voting_result[:result]}"


        - if can?(:update, answer)
          %li
            = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
            = link_to 'Delete', answer_path(answer), method: :delete, remote: true

          %p
            = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
              = f.label :body, 'Answer'
              = f.text_area :body

              #attachments
                = f.fields_for :attachments do |attachment|
                  = render 'shared/attachments', f: attachment
                .links
                  = link_to_add_association 'add file', f, :attachments, partial: 'shared/attachments'
              %br
              = f.submit 'Save'

        = render 'shared/comment', commentable: answer

      %hr

app/views/answers/create.js.erb
<% if @answer.errors.any? %>
$('.errors').html('<%= j render 'shared/errors', object: @answer %>');
<% else %>
$('.flash').html('<%= j render 'shared/flash' %>');
$('.answers').append('<%= j render @answer %>');
$('.answer-create #answer_body').val('');
$('.edit-answer-link').click(function(e) {
    e.preventDefault();
    $(this).hide();
    var answer_id = $(this).data('answerId');
    $('form#edit-answer-' + answer_id).show();
});
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.errors.any? %>
  $('.errors').html('<%= j render 'shared/errors', object: @answer %>');
<% else %>
  $('.flash').html('<%= j render 'shared/flash' %>');
  $('.answer-' + <%= @answer.id %>).remove();
<% end %>

app/views/answers/set_the_best.js.erb
$('.answers').html('<%= j render @question.answers.sorted %>');

app/views/answers/update.js.erb
<% if @answer.errors.any? %>
  $('.errors').html('<%= j render 'shared/errors', object: @answer %>');
<% else %>
  $('.flash').html('<%= j render 'shared/flash' %>');
  $('.answer-' + <%= @answer.id %>).html('<%= j render @answer %>');
  $('.edit-answer-link').click(function(e) {
      e.preventDefault();
      $(this).hide();
      var answer_id = $(this).data('answerId');
      $('form#edit-answer-' + answer_id).show();
  });
<% end %>